### ISSUE TITLE
No hdf file created during posture detection

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/iblvideo#14]
`d23a44ef-1402-4ed7-97f5-47e9a7a504d9`
`93ad879a-aa42-4150-83e1-38773c9785e4`
`d55a4fbe-c40c-4c06-ad0b-e4defd6197f3`

For all three videos of these sessions, the following error occurs: 
```
2021-07-06 16:42:18,533,533 INFO     [choiceworld.py:172] STEP 02 START Posture detection for _iblrig_rightCamera.subsampled.mp4
2021-07-06 16:42:22,050,50 INFO     [choiceworld.py:177] STEP 02 END Posture detection for _iblrig_rightCamera.subsampled.mp4
2021-07-06 16:42:22,050,50 INFO     [choiceworld.py:196] STEP 03 START generating cropped video _iblrig_rightCamera.nose_tip.mp4
2021-07-06 16:42:22,050,50 ERROR    [run.py:119] DLC rightCamera failed.
Traceback (most recent call last):
  File "/home/mic/miniconda3/envs/DLC-GPU/lib/python3.7/site-packages/iblvideo/run.py", line 115, in _run
    dlc_timer=timer[f'{cam}'])
  File "/home/mic/miniconda3/envs/DLC-GPU/lib/python3.7/site-packages/iblvideo/choiceworld.py", line 389, in dlc
    networks[k], force=force)
  File "/home/mic/miniconda3/envs/DLC-GPU/lib/python3.7/site-packages/iblvideo/choiceworld.py", line 199, in _s03_crop_videos
    whxy = _get_crop_window(file_df_crop, network)
  File "/home/mic/miniconda3/envs/DLC-GPU/lib/python3.7/site-packages/iblvideo/choiceworld.py", line 75, in _get_crop_window
    df_crop = pd.read_hdf(file_df_crop)
  File "/home/mic/miniconda3/envs/DLC-GPU/lib/python3.7/site-packages/pandas/io/pytables.py", line 387, in read_hdf
    "Support for generic buffers has not been implemented."
NotImplementedError: Support for generic buffers has not been implemented.
```
The issue seems to be that no hdf file is created in Step 2. Unclear why, would be good to check the raw videos, and run one of the sessions "by hand" to see the full output

**Comment by juhuntenburg** [comment]
Ran through without problem on second try, unclear what happenend. Closing this
